// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTY922LiqHyfjByEn7e1696T-NztkpC3E',
    appId: '1:278713947655:web:e40f3c769bd8df0135fca2',
    messagingSenderId: '278713947655',
    projectId: 'whatsapp-clone-v2-db637',
    authDomain: 'whatsapp-clone-v2-db637.firebaseapp.com',
    storageBucket: 'whatsapp-clone-v2-db637.appspot.com',
    measurementId: 'G-JEFJVJGBF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyKLS-NrgqTwT0Fe3ZpwHRwWFIG7jiRs',
    appId: '1:278713947655:android:6ac5deea8c4e5de135fca2',
    messagingSenderId: '278713947655',
    projectId: 'whatsapp-clone-v2-db637',
    storageBucket: 'whatsapp-clone-v2-db637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3K3G5ypYT428_4xZSwgQpC9JqgKcvYrg',
    appId: '1:278713947655:ios:afe8cb9847aceb7735fca2',
    messagingSenderId: '278713947655',
    projectId: 'whatsapp-clone-v2-db637',
    storageBucket: 'whatsapp-clone-v2-db637.appspot.com',
    androidClientId: '278713947655-nm4bi4mhsulb923b9l40hdbvnga7midb.apps.googleusercontent.com',
    iosClientId: '278713947655-1a3sspqmianlh6tfoqjn757d5cjmn7m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
